kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: web
  labels:
    app: hub-controller-live
    app.kubernetes.io/instance: hub-controller
spec:
  to:
    kind: Service
    name: hub-controller-live
    weight: 100
  port:
    targetPort: http

