---

- name: Create ODF Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-namespace.yml' ) | from_yaml }}"
  tags: odf

- name: Enable Monitoring for storage namespace
  command: oc label namespace openshift-storage openshift.io/cluster-monitoring="true" --overwrite 
  tags: odf

- name: Create ODF OperatorGroup
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'operator-group.yml' ) | from_yaml }}"
  tags: odf

- name: Install ODF Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'operator-subscription.yml' ) | from_yaml }}"
  tags: odf

- name: Discovering worker nodes
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: v1
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/worker
  register: worker_nodes
  tags: odf

- fail:
    msg: "Less than 3 worker nodes detected. Cannot install Ceph..."
  when: worker_nodes.resources | length < 3
  tags: odf

- set_fact:
    ceph_worker_nodes: "{{ worker_nodes | json_query('resources[*].metadata.name') }}"
  tags: odf

- name: "Adding Ceph labels to worker nodes"
  shell: "oc label nodes --overwrite {{ item }} cluster.ocs.openshift.io/openshift-storage=''"
  loop: "{{ ceph_worker_nodes }}"
  tags: odf
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig }}"

- name: "Get Installed CSV"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "odf-operator"
    namespace: "openshift-storage"
  register: r_subscription
  retries: 30
  delay: 5
  until:
    - r_subscription.resources[0].status.currentCSV is defined
    - r_subscription.resources[0].status.currentCSV | length > 0
  tags: odf

- name: "Wait until CSV is installed"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "openshift-storage"
  register: r_csv
  retries: 30
  delay: 30
  until:
    - r_csv.resources[0].status.phase is defined
    - r_csv.resources[0].status.phase | length > 0
    - r_csv.resources[0].status.phase == "Succeeded"
  tags: odf

- name: Enable Console Plugin
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'console-plugin.yml' ) | from_yaml }}"
  tags: odf

- name: Include ODF CustomResource instances
  include_tasks: "install-odf-custom-resource-instances.yml"
  tags: odf

  